### ISSUE TITLE
Class Cast Exception from passgrade.

### ISSUE THREAD

**Issue by chibill** [PizzaCrust/Fernfertilizer#2]
java -jar Fernfertilizer-2.0-SNAPSHOT.jar -1 server.jar -2 spigot-1.11.2.jar -p 90
Passing percentage grade is set to: 90
NOTICE: Writing output SRG to: C:\Users\chibi\Downloads\target.srg
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.Integer;
        at online.pizzacrust.fernfertilizier.ClassComparator.compare(ClassComparator.java:35)
        at online.pizzacrust.fernfertilizier.LogicJarComparator.generateMappings(LogicJarComparator.java:30)
        at online.pizzacrust.fernfertilizier.LogicJarComparator.writeTo(LogicJarComparator.java:69)
        at online.pizzacrust.fernfertilizier.Main.main(Main.java:41)

**Comment by PizzaCrust** [comment]
Weird, I'm going to try to reproduce this.

**Comment by chibill** [comment]
This happens no matter what jars I input.

**Comment by PizzaCrust** [comment]
The code doesn't match the latest version. Please try again using the latest commit and building it yourself.

**Comment by chibill** [comment]
I built it myself (downloaded the repo) right before finding this bug. But I will try again when I get home.

**Comment by PizzaCrust** [comment]
Oh, I think I didn't commit the fixes... *facepalm*

**Comment by chibill** [comment]
Oh. Lol. I will test it out later Once you push.

**Comment by PizzaCrust** [comment]
weird intellij says the line is different and github says different idk now

**Comment by PizzaCrust** [comment]
oh facepalm its on another branch

**Comment by chibill** [comment]
Okay.  Branches all ways mess me up.

**Comment by PizzaCrust** [comment]
still i thinks its a issue, i'm going to try to reproduce in case it hasnt been fixed in the new branch

**Comment by chibill** [comment]
Okay. Just so you know I used the master branch. So I know it's not fixed there.

**Comment by PizzaCrust** [comment]
there are more issues than i tested originally in the new branch, i'll have it ready by tmrw

**Comment by PizzaCrust** [comment]
Master has been merged with the fixes and new features of the newalgorithm branch. Reopen this issue if you continue to have this specific problem.

**Comment by chibill** [comment]
All good it works. The actual matcher still needs some work maybe... (Can't even match to identical jars very well to each other. with a pg of 80)

**Comment by PizzaCrust** [comment]
Ya, it would be nice if you could help 😄

**Comment by chibill** [comment]
I am not much help. But one thing is to just match any files that have identical md5 hashes as a start.

**Comment by PizzaCrust** [comment]
Hmm.. I'll push that later on the day.

**Comment by chibill** [comment]
That's what I use in my mapping system along with string and number constant matching

**Comment by PizzaCrust** [comment]
you should try field mapping, its about 85% accurate with --samemodifiers true argument
